baseURL = "https://utb.vilhelmprytz.se/"
languageCode = "sv"
DefaultContentLanguage = "sv"
title = "Vilhelm Prytz - Utbildningsmaterial"

theme = "book"

[params]
    BookRepo = 'https://github.com/VilhelmPrytz/utbildningsmaterial'
    BookEditPath = 'edit/master/content'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
